services:
  gateway:
    build: ./services/gateway
    ports: ["8080:8080"]
    environment:
      - SERVICE_NAME=gateway
      - PEP_URL=http://pep:8080
      - RAG_URL=http://rag:8080
      - AIMS_URL=http://aims:8080
    depends_on: [ pep, rag, aims ]

  pep:
    build: ./services/pep
    ports: ["8084:8080"]
    environment:
      - SERVICE_NAME=pep
      - PDP_URL=http://aims:8080

  aims:
    build: ./services/aims
    ports: ["8090:8080"]
    environment:
      - SERVICE_NAME=aims

  rag:
    build: ./services/rag
    ports: ["8081:8080"]
    environment:
      - SERVICE_NAME=rag
      - TOOLS_URL=http://tools:8080
      - MODELS_URL=http://models:8080

  tools:
    build: ./services/tools
    ports: ["8082:8080"]
    environment:
      - SERVICE_NAME=tools

  models:
    build: ./services/models
    ports: ["8083:8080"]
    environment:
      - SERVICE_NAME=models
